name: Deploy Lambda on Git Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Deploy Lambda Function
      run: sh update-lambda.sh
        
